config/routes.rb
Rails.application.routes.draw do
	devise_for :users

	mount ActionCable.server => '/cable'

	resources :buddies
	resources :messages
	root 'buddies#index'

	get 'undelivered' => 'messages#undelivered'
	
	
	
	

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  has_many :messages	
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :buddy, optional: true
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	
	def auto_html(m)
		img_filter = AutoHtml::Image.new
		link_filter = AutoHtml::Link.new(target: '_blank')
		emoji_filter = AutoHtml::Emoji.new	  
		base_format = AutoHtml::Pipeline.new(img_filter, emoji_filter, link_filter)
		base_format.call(m).html_safe
	end	
	helper_method :auto_html
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_buddy, only: [:show, :edit, :update, :destroy]

  # GET /buddies
  # GET /buddies.json
  def index
    @buddies = Buddy.all
  end

  # GET /buddies/1
  # GET /buddies/1.json
  def show
	@buddy = Buddy.find(params[:id])
	@messages = @buddy.messages.last(40) #list all messages from/to buudy
	@message = Message.new #new message
	@message.fullname = @buddy.fullname
	@message.buddyid = @buddy.buddyid
	@message.buddy_id = @buddy.id
	@message.sent = true
  end

  # GET /buddies/new
  def new
    @buddy = Buddy.new
  end

  # GET /buddies/1/edit
  def edit
  end

  # POST /buddies
  # POST /buddies.json
  def create
    @buddy = Buddy.new(buddy_params)

    respond_to do |format|
      if @buddy.save
        format.html { redirect_to @buddy, notice: 'Buddy was successfully created.' }
        format.json { render :show, status: :created, location: @buddy }
      else
        format.html { render :new }
        format.json { render json: @buddy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buddies/1
  # PATCH/PUT /buddies/1.json
  def update
    respond_to do |format|
      if @buddy.update(buddy_params)
        format.html { redirect_to @buddy, notice: 'Buddy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buddy }
      else
        format.html { render :edit }
        format.json { render json: @buddy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buddies/1
  # DELETE /buddies/1.json
  def destroy
    @buddy.destroy
    respond_to do |format|
      format.html { redirect_to buddies_url, notice: 'Buddy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buddy
      @buddy = Buddy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buddy_params
      params.require(:buddy).permit(:fullname, :buddyid)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!, except: [:undelivered, :update, :create]
	before_action :set_message, only: [:show, :edit, :update, :destroy]
	skip_before_action :verify_authenticity_token

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

	def undelivered
    	@messages = Message.where(sent: true, delivered: false)
	end	
	
  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
	@message = Message.new(message_params)
	@buddy = Buddy.find_or_create_by(buddyid: @message.buddyid)
	@message.buddy_id = @buddy.id
	@buddy.update(fullname: @message.fullname) if (@buddy.fullname.blank? && !@message.fullname.blank?)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @buddy, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
	
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :fullname, :buddyid, :sent, :received, :delivered, :buddy_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buddies_helper.rb
module BuddiesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/buddies/_form.html.erb
<%= form_for(buddy) do |f| %>
  <% if buddy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buddy.errors.count, "error") %> prohibited this buddy from being saved:</h2>

      <ul>
      <% buddy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %>
    <%= f.text_field :fullname %>
  </div>

  <div class="field">
    <%= f.label :buddyid %>
    <%= f.text_field :buddyid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buddies/_hidden_div.html.erb
 <!-- created hidden box due to padding bottom not showing -->
<div id="hidden-box">
	<p>.</p>
	<br>
	<br>
	<br>
	<p>.</p>
</div>

app/views/buddies/edit.html.erb
<% if current_user.admin? %> 
	<h1>Editing Buddy</h1>

	<%= render 'form', buddy: @buddy %>

	<%= link_to 'Show', @buddy %> |
	<%= link_to 'Back', buddies_path %>
<% end %>

app/views/buddies/index.html.erb
<div class=" col-xs-12 scrollable-div">
	<% @buddies.each do |buddy| %>
		<%= link_to buddy.fullname, buddy, :class => 'fullname' %>
		<p id="last-msg" class="text-overflow"><%= buddy.messages.last.content %></p>					
		<hr>
	<% end %>
	<%= render "hidden_div" %>
</div>

<% if current_user.admin? %> 
	<div class="developer-mode">
		<table>
		  <thead>
			<tr>
			  <th>Fullname</th>
			  <th>Buddyid</th>
			  <th colspan="3"></th>
			</tr>
		  </thead>

		  <tbody>
			<% @buddies.each do |buddy| %>
			  <tr>
				<td><%= buddy.fullname %></td>
				<td><%= buddy.buddyid %></td>
				<td><%= link_to 'Show', buddy %></td>
				<td><%= link_to 'Edit', edit_buddy_path(buddy) %></td>
				<td><%= link_to 'Destroy', buddy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>

		<%= link_to 'New Buddy', new_buddy_path %>	
	</div>
<% end %>

app/views/buddies/new.html.erb
<% if current_user.admin? %> 
	<h1>New Buddy</h1>

	<%= render 'form', buddy: @buddy %>

	<%= link_to 'Back', buddies_path %>
<% end %>

app/views/buddies/show.html.erb
<div id="msg-container" class="scrollable-div">
	<%= content_tag :div, :id => 'messages', :data => {'buddy-id' => @buddy.id, 'buddyid' => @buddy.buddyid} do -%>
		<%= render @messages %>
	<% end -%>
	<%= render "hidden_div" %>
</div>

<div class="input-group navbar-fixed-bottom">
	<input id="chat-bar" type="text" class="form-control " placeholder="Type a message" data-behavior="buddy_speaker"> 
	<div id="send-btn" class="input-group-addon">
		<span class="glyphicon glyphicon-send" aria-hidden="true"></span>
	</div>
</div>

<% if current_user.admin? %> 
	<div class="developer-mode">
		<strong>Buddyid:</strong>
		<%= @buddy.buddyid %>
		<%= render 'messages/form', message: @message %>
		<%= link_to 'Back to Messages', messages_path %> |
		<%= link_to 'Edit Buddy', edit_buddy_path(@buddy) %>	
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messages</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<%= link_to '', buddies_path, :class => 'navbar-brand glyphicon glyphicon glyphicon-home' %>

				<% if current_page?(buddies_path) || current_page?(root_path) %>
					<p class="navbar-text fullname">Messages</p>

				<% elsif current_page?(messages_path) || current_page?(new_user_session_path) || current_page?(new_user_registration_path) || current_page?(edit_user_registration_path) || current_page?(destroy_user_session_path) %>

				<% else %>
					<p class="navbar-text fullname"><%= @buddy.fullname %></p>
				<% end %>
			</div>			
		</div>			
	</nav>
		  
	<div class="container-fluid">
		<div class="row">
			<%= yield %>
		</div>
	</div>		  
	  
	<div class="developer-mode">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>	  		
		<% if user_signed_in? %>
		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>	  
	</div>	  
	  
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= f.label :content %>
		<%= f.text_area :content %>
	</div>

	<div class="field">
		<%= f.label :fullname %>
		<%= f.text_field :fullname %>
	</div>

	<div class="field">
		<%= f.label :buddyid %>
		<%= f.text_field :buddyid %>
	</div>

	<div class="field">
		<%= f.label :buddy_id %>
		<%= f.text_field :buddy_id %>
	</div>

	<div class="field">
		<%= f.label :sent %>
		<%= f.check_box :sent %>
	</div>

	<div class="field">
		<%= f.label :received %>
		<%= f.check_box :received %>
	</div>

	<div class="field">
		<%= f.label :delivered %>
		<%= f.check_box :delivered %>
	</div>		

	<div class="actions">
		<%= f.submit %>
	</div>		
<% end %>

app/views/messages/_message.html.erb
<% cache message do %>
	<div class=" col-xs-12">
		<%= content_tag :div, :class => 'message img-thumbnail' + (message.sent ? ' sent ' : ' received ')  do -%>
			<%= auto_html(message.content) %>
		<% end -%>		
	</div>
<% end %>

<div class="developer-mode">
	<%= link_to "See more", message_path(message) %>
</div>

app/views/messages/edit.html.erb
<% if current_user.admin? %> 
	<h1>Editing Message</h1>

	<%= render 'form', message: @message %>

	<%= link_to 'Show', @message %> |
	<%= link_to 'Back', messages_path %>
<% end %>

app/views/messages/index.html.erb
<% if current_user.admin? %> 
	<h1>Messages</h1>

	<table>
	  <thead>
		<tr>
		  <th>Content</th>
		  <th>Fullname</th>
		  <th>Buddyid</th>
		  <th>Sent</th>
		  <th>Received</th>
		  <th>Delivered</th>
		  <th>Buddy</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

	  <tbody>
		<% @messages.each do |message| %>
		  <tr>
			<td><%= message.content %></td>
			<td><%= message.fullname %></td>
			<td><%= message.buddyid %></td>
			<td><%= message.sent %></td>
			<td><%= message.received %></td>
			<td><%= message.delivered %></td>
			<td><%= message.buddy %></td>
			<td><%= link_to 'Show', message %></td>
			<td><%= link_to 'Edit', edit_message_path(message) %></td>
			<td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		  </tr>
		<% end %>
	  </tbody>
	</table>

	<br>

	<%= link_to 'New Message', new_message_path %>

	<script type="text/javascript">

	  $.getJSON('http://localhost:3000/messages', function(data) {
		  console.log(data[0]);
	  });
	  <%# 

	  $.ajax({ 
		url: "http://localhost:3000/messages", dataType: "jsonp", type: "POST", data: { message: { 
		  content: "xxss" 
		}}
	  });
	  %> 

	</script>
<% end %>

app/views/messages/new.html.erb
<% if current_user.admin? %> 
	<h1>New Message</h1>

	<%= render 'form', message: @message %>

	<%= link_to 'Back', messages_path %>
<% end %>

app/views/messages/show.html.erb
<% if current_user.admin? %> 
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Content:</strong>
	  <%= @message.content %>
	</p>

	<p>
	  <strong>Fullname:</strong>
	  <%= @message.fullname %>
	</p>

	<p>
	  <strong>Buddyid:</strong>
	  <%= @message.buddyid %>
	</p>

	<p>
	  <strong>Sent:</strong>
	  <%= @message.sent %>
	</p>

	<p>
	  <strong>Received:</strong>
	  <%= @message.received %>
	</p>

	<p>
	  <strong>Delivered:</strong>
	  <%= @message.delivered %>
	</p>

	<p>
	  <strong>Buddy:</strong>
	  <%= @message.buddy %>
	</p>

	<%= link_to 'Edit', edit_message_path(@message) %> |
	<%= link_to 'Back', messages_path %>
<% end %>